FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir flask pandas numpy

COPY service_preprocessor.py .
RUN mkdir -p /app/data/incoming

EXPOSE 5000
CMD ["python", "service_preprocessor.py"]
