FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY model.pkl .
COPY service_classifier.py .

RUN mkdir -p /app/data/incoming \
    /app/data/processing \
    /app/data/processed \
    /app/data/errors \
    /app/data/results

CMD ["python", "service_classifier.py"]
